### ISSUE TITLE
Cannot resolve symbol LuPlus_component during preview

### ISSUE THREAD

**Issue by TonyHg** [qwikest/icons#5]
# Cannot resolve symbol LuPlus_component

I started working on an app using Qwik,

I built the app using `npm run build` then I tried to run the preview by doing `npm run preview` but got `Cannot resolve symbol LuPlus_component in ...`

## Steps to Reproduce
1. git clone `https://github.com/TonyHg/qwik-todo`
2. `cd qwik-todo`
3. `npm run build`
4. `npm run preview`

## Detailed Description
```
Cannot resolve symbol LuPlus_component_0pJJ4mFYWEc in {
  '02wMImzEAbk': [ 's_02wMImzEAbk', 'q-419c31bb.js' ],
  LfwvGfSr5Xo: [ 's_LfwvGfSr5Xo', 'q-04872755.js' ],
  c8vKjf2z5qc: [ 's_c8vKjf2z5qc', 'q-51d01095.js' ],
  ...
      uYtGD160U1w: [ 's_uYtGD160U1w', 'q-23b146d1.js' ],
    wtUslpItYss: [ 's_wtUslpItYss', 'q-04872755.js' ]
}
QWIK ERROR Error: Code(31)
at createError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:70:17)
at logError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:64:54)
at logErrorAndStop (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:74:17)
at qError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:137:12)
at serializeQRL (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:515:15)
at Object.serialize (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6116:16)
at serializeValue (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6376:28)
at file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4242:23
    at Array.map (<anonymous>)
  at _pauseFromContexts (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4225:32) LuPlus_component_0pJJ4mFYWEc
  Error: Code(31)
  at createError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:70:17)
  at logError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:64:54)
  at logErrorAndStop (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:74:17)
  at qError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:137:12)
  at serializeQRL (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:515:15)
  at Object.serialize (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6116:16)
  at serializeValue (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6376:28)
  at file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4242:23
  at Array.map (<anonymous>)
    at _pauseFromContexts (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4225:32)
    Error: Code(31)
    at createError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:70:17)
    at logError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:64:54)
    at logErrorAndStop (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:74:17)
    at qError (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:137:12)
    at serializeQRL (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:515:15)
    at Object.serialize (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6116:16)
    at serializeValue (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:6376:28)
    at file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4242:23
    at Array.map (<anonymous>)
      at _pauseFromContexts (file:/qwik-todo/node_modules/@builder.io/qwik/core.mjs:4225:32

```

**Comment by TonyHg** [comment]
fixed by removing conditional class on Icon
```typescript
// Fail
<LuPlus class={isLoading ? 'loading' : ''}
```
